import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 15,
    paddingHorizontal: 20,
  },
  statItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 8,
    padding: 10,
    minWidth: 120,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#666',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1a237e',
  },
  comboContainer: {
    backgroundColor: '#e91e63',
    borderRadius: 8,
    padding: 10,
    marginLeft: 15,
    minWidth: 100,
    alignItems: 'center',
  },
  comboText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  boxerContainer: {
    height: 220,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  boxerImage: {
    width: 250,
    height: 220,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'black',
  },
  controlsContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.03)',
    borderRadius: 16,
    padding: 15,
    marginVertical: 10,
  },
  controlsTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#666',
    marginBottom: 15,
    textAlign: 'center',
  },
  moveButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  moveButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  kickButton: {
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  moveButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
  },
});
